### ISSUE TITLE
リファクタリング: ユースケース「システム管理コンソールへログインする」の実装に先立っての細かい修正

### ISSUE THREAD

**Issue by Kimita** [clap-and-whistle/ci-test-for-laravel#21]
# 対応の概要

- [x]  例外クラスの配置を見直す
    - [x]  ビジネスロジック層で使用する例外クラスの内、 infra層へ配置されている例外クラスをビジネスロジック層へ移す
    - [x]  ビジネスロジック層内でのパスワード系例外を、個別の集約単位ではなくRegistrationProcessFailedExceptionと同じ階層へ移す
- [x]  アプリケーションのinfra層配下に置いた単体テスト用のクラスを、テストのinfra層配下へ移す
- [x] User集約の構築タイミングを変更する
    - [x] ログイン完了後の遷移先ページへのアクセスをテストするインテグレーションテストのコードを作成する
    - [x] 一般ユーザ新規作成時の入力画面からのPOST処理に対するインテグレーションテストのコードを修正する
    - [x] 設計資料を修正する
        - [x] 共通版
            - [x] 一般ユーザアカウント管理機能_概念モデル図
            - [x] ユースケース記述
            - [x] ロバストネス図
            - [x] シーケンス図
            - [x] クラス図
        - [x] Laravel版
            - [x] シーケンス図
            - [x] クラス図
    - [x] ログイン完了後の遷移先ページで集約インスタンスの構築を実行する
    - [x] 一般ユーザ新規作成時にも save()処理の最後にUser集約インスタンスの構築まで実行する
        - [x] save()時のトランザクション制御付加が漏れていたので加える
- [x] ついでに、関連クラスにIDEからの警告などがあれば極力直す

**Comment by clap-and-whistle** [comment]
#22 用作業ブランチへのマージが済んだのでクローズ
