### ISSUE TITLE
ユースケース「システム管理コンソールへログインする」のビジネスロジック処理を実装する

### ISSUE THREAD

**Issue by Kimita** [clap-and-whistle/ci-test-for-laravel#23]
# 対応の概要

#22  で作成した設計資料のシーケンス図・クラス図に記載の内容の通りに実装する。

1. モデリング済みのクラス群を、ひとまず骨組みだけ実装する
2. 実装したクラス群(の骨組みだけ)を使ったテストコードを書く（この時点ではすべてのテストがfailして構わない）
3. 実装の詳細を仕上げつつ、テストコードに考慮不足があったら補いながら完成させる。

**Comment by clap-and-whistle** [comment]
devブランチへのマージを終えたのでクローズします。
