### ISSUE TITLE
ユースケース「システム管理コンソールへログインする」: ビジネスロジック処理をプレゼンテーション層へ繋ぎ込み

### ISSUE THREAD

**Issue by Kimita** [clap-and-whistle/ci-test-for-laravel#24]
# 対応の概要

#23  で実装したビジネスロジック処理をcontrollerへ組み込み、ユーザが操作するためのviewを実装し、セキュリティ設定を追加する。

- まずはインテグレーションテストを書く。
- ルーティング設定で一般ユーザ向けURLとシステム管理者向けURLとを区別して記述する。
- ビジネスロジック処理が成功を返した場合に認証セッションを開始する。
     - 失敗を返した場合はログイン画面へ戻す。

# staging前のTODO

- [x] セキュリティ設定の変更が、認証不要な領域へ悪影響を及ぼしていないか確認する。
- [x] migrationファイルとseederファイルを作成する

**Comment by clap-and-whistle** [comment]
devブランチへのマージを終えたのでクローズします。
